# SPDX-FileCopyrightText: 2024 simple_sat contributors <https://github.com/ash-project/simple_sat/graphs.contributors>
#
# SPDX-License-Identifier: MIT

version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: "daily"
