# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    with:
      spark-formatter: false
      spark-cheat-sheets: false
      reuse: true
      igniter-upgrade: false
